on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yaml
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
