on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy_npm:
    needs: test
    uses: ./.github/workflows/deploy_to_npm.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy_crates:
    needs: test
    uses: ./.github/workflows/deploy_to_crates.yaml
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
